method:
  name : "DPO"

model:
  model_path: "stabilityai/stable-diffusion-2-1"
  pipeline_kwargs:
    use_safetensors: True
    variant: "fp16"
  sdxl: False
  model_arch_type: "LDMUnet"
  attention_slicing: True
  xformers_memory_efficient: False
  gradient_checkpointing: True
  

sampler:
  guidance_scale: 7.5
  num_inference_steps: 50

optimizer:
  name: "adamw"
  kwargs:
    lr: 2.048e-8
    weight_decay: 1.0e-4
    betas: [0.9, 0.999]

scheduler:
  name: "linear" # Name of learning rate scheduler
  kwargs:
    start_factor: 1.0
    end_factor: 1.0
  
logging:
  run_name: 'dpo_pickapic'
  #wandb_entity: None
  #wandb_project: None

train:
  num_epochs: 500
  num_samples_per_epoch: 256
  batch_size: 4
  target_batch: 256
  checkpoint_interval: 640
  tf32: True
  suppress_log_keywords: "diffusers.pipelines,transformers"
